project:
  type: book
  output-dir: _book

book:
  title: "Close the Loop"
  sidebar:
    style: docked
    background: white
  author:
  - name: "William Chavarría"
    orcid: 0009-0001-4084-9290
  date: "9/28/2023"

  page-footer:
    left: |
      Close the Loop (CTL) fue escrito por William Chavarría
    right: |
      Universidad del Valle de Guatemala <a href="https://www.uvg.edu.gt/">UVG</a>.
  cover-image: cover.jpg
  favicon: fav.jpg
  repo-url: https://github.com/yunkel09/yunkel09.github.io
  repo-branch: master
  chapters:
    - index.qmd


    - intro.qmd

    - part: data-adquisition.qmd
      chapters:
        - data-collection.qmd
        - data-import.qmd
        - data-dictionary.qmd

    - part: visualize.qmd
      chapters:
        - data-prep.qmd
        - split.qmd
        - eda.qmd

    - part: modeling.qmd
      chapters:
        - cross-validation.qmd
        - preprocessing.qmd
        - model-specification.qmd
        - model-training.qmd
        - model-evaluation.qmd

    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    mermaid:
      theme: forest
    highlight-style: breeze
    toc-expand: true
    # cap-location: margin
    theme:
      - cosmo
      - ctl.scss

    author-meta: "William Chavarría, André Rodas, Francisco Manjon y Pablo Armas"
    callout-appearance: default