# Prefacio {.unnumbered}

El proyecto busca desarrollar un modelo de machine learning para analizar y
clasificar automáticamente las respuestas de las encuestas de NPS (Net
Promoter Score) en Tigo Guatemala. El objetivo es utilizar estos insights
para guiar decisiones estratégicas en áreas como inversión en
infraestructura, optimización de red y mejora de la calidad del servicio.
Al hacerlo, la empresa espera mejorar la percepción del cliente, medida a
través del NPS, y en última instancia, aumentar la lealtad del cliente y el
retorno de inversión (ROI).

En Tigo, medimos el Quality of Service (QoS) utilizando encuestas de Net
Promoter Score (NPS) de tipo transaccional, las cuales evalúan la
experiencia reciente del usuario con la calidad de nuestra red. Un día
después de recibir las respuestas, un equipo de analistas, el Close The
Loop, agrega un diagnóstico basado en métricas de red para representar la
posible causa del Poor User Experience para cada cliente encuestado. Las
posibles causas están categorizadas en: Capacidad, Cobertura, Optimización,
Transmisión, Disponibilidad y No detractor.

Se tiene un NPS Transaccional de red móvil que está impactando en el
revenue y aumenta la taza de abandono de los clientes. Actualmente existe
un equipo llamado CTL que analiza las encuestas y los KPIs de red con el
fin de realizar una clasificación manual de los diagnósticos de los
usuarios detractores de red. Posteriormente, se realizan acciones
correctivas. 